### ISSUE TITLE
Latest Release 2.0.0 Missing from Nuget Repo

### ISSUE THREAD

**Issue by mitchellmaler** [jaxxstorm/pulumi-rke#44]
The Pulumi.Rke Nuget for 2.0.0 is missing after the latest release.
https://www.nuget.org/packages/Pulumi.Rke

I was working on upgrading my stacks and noticed only 1.0.1 was available.

**Comment by jaxxstorm** [comment]
An alpha version should now be there, and the nuget publishing is fixed
